# Conexion MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3306/zona_fit_db
spring.datasource.username=root
spring.datasource.password=Cyber2Dragon@
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# Evitar que se cree el esquema de bd
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
#banner
spring.main.banner-mode=off
# Configuración del logging en consola con el mismo patrón de Logback
logging.pattern.console=[%thread] %-5level: %logger - %msg%n
logging.level.root=INFO
# Tema de primefaces, por default tema de saga
joinfaces.primefaces.theme=vela

spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect